### ISSUE TITLE
Automated rendering seems to be broken

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#103]
As reported by @stuart-robinson:

```
cat global/originations_platform/orginations_platform_02_container.yaml | fc4-render --verbose
launching browser...
loading Structurizr Express from https://structurizr.com/express?autoLayout=false...
setting YAML and updating diagram...
calling export function...
(node:43666) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'crop' of undefined
    at Structurizr.DiagramScripting.exportCurrentDiagramToPNG (https://structurizr.com/static/js/structurizr-scripting-diagram.js?v=1380:13:59)
    at __puppeteer_evaluation_script__:2:34
    at ExecutionContext.evaluateHandle (/snapshot/root/project/tool/renderer/node_modules/puppeteer-core/lib/ExecutionContext.js:106:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:43666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43666) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I suspect Structurizr Express may have changed. I will investigate shortly.

**Comment by aviflax** [comment]
Also, TODO: create another issue about the failure mode of `fc4 render` in cases like these… apparently it just hangs. That’s no good. It should fail fast and explicitly with a nonzero exit code and an error message.
