### ISSUE TITLE
Exceptions inside clipboard go-loop

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#12]
When a `go-loop` is watching the clipboard for diagram and processing them, if an exception is thrown then the block exits

It should rather just print out the error and then continue.

Example output in the REPL:

```
user=> (start)
nil
user=> 12:51:36 -> processed System Context for FC App with great success!
Exception in thread "async-dispatch-7" java.lang.Error: java.awt.datatransfer.UnsupportedFlavorException: Unicode String
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.awt.datatransfer.UnsupportedFlavorException: Unicode String
	at sun.awt.datatransfer.ClipboardTransferable.getTransferData(ClipboardTransferable.java:159)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at fc4c.clipboard$slurp.invokeStatic(clipboard.clj:10)
	at fc4c.clipboard$slurp.invoke(clipboard.clj:8)
	at fc4c.repl$start$fn__10895$state_machine__6412__auto____10896$fn__10898.invoke(repl.clj:60)
	at fc4c.repl$start$fn__10895$state_machine__6412__auto____10896.invoke(repl.clj:60)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__6430.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__658.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 2 more
```

**Comment by aviflax** [comment]
I haven’t seen this happen for a long time, so closing for now. If it happens again we can reopen.
